services:
  mongo:
    image: mongo:4.4.21
    restart: always
    network_mode: host
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.4.2
    restart: always
    network_mode: host
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
    external: true
  redis_data:
    external: true
