services:
  mongo:
    image: mongo:4.4.21
    restart: always
    network_mode: host
    volumes:
      - ~/docker-data/mongo/db:/data/db

  redis:
    image: redis:7.4.2
    restart: always
    network_mode: host
    volumes:
      - ~/docker-data/redis:/data
